[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "frametree-flywheel"
description = "Description for frametree-flywheel goes here"
readme = "README.rst"
requires-python = ">=3.8"
dependencies = [
    "frametree >=0.9.4",
    "flywheel-sdk ==16.8.16"
]
license = {file = "LICENSE"}
authors = [
    {name = "Aaron Capon", email = "aaron.capon@florey.edu.au"},
    {name = "Thomas Close", email = "tom.g.close@gmail.com"}
]
maintainers = [{name = "Aaron Capon", email = "aaron.capon@florey.edu.au"}]
keywords = ["frametree"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "black",
    "codespell",
    "flake8",
    "flake8-pyproject",
    "pre-commit",
]
doc = [
    "docutils>=0.10",
    "furo>=2022.2.14.1",
    "mock>1.0",
    "numpydoc>=0.6.0",
    "packaging",
    "sphinx >=2.1.2",
    "sphinx-argparse>=0.2.0",
    "sphinx-click>=3.1",
]
test = [
    "fileformats",
    "fileformats-testing",
    "pytest >= 4.4.0",
    "pytest-cov",
    "pytest-env",
]

[project.urls]
documentation = "https://frametree.readthedocs.io"
homepage = "https://frametree.readthedocs.io"
# repository = "https://github.com/ArcanaFramework/frametree-flywheel.git"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "frametree/flywheel/_version.py"

[tool.hatch.build]
packages = [
    "frametree",
]
exclude = [
    "/tests",
]

[tool.black]
line-length = 88
target-version = ["py38"]
exclude = "_version.py"

[tool.codespell]
ignore-words = ".codespell-ignorewords"
